@extends('layouts.authenticated')
@section('title', 'Registrar solicitud')
@section('content')
<div class="mb-4"><nav aria-label="Ruta de navegación"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{ route('dashboard.applicant') }}">Panel</a></li><li class="breadcrumb-item active">Registrar solicitud</li></ol></nav><h1 class="h2">Registrar nueva solicitud</h1><p class="text-secondary">La información y los documentos cambian según el trámite configurado.</p></div>

<section class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h2 class="h5">1. Categoría y trámite</h2><form class="row g-3" method="GET" action="{{ route('applicant.procedure-requests.create') }}"><div class="col-md-9"><label class="form-label" for="tipo">Trámite disponible</label><select class="form-select" id="tipo" name="tipo" required><option value="">Selecciona una opción</option>@foreach($procedureTypes->groupBy(fn($type) => $type->category?->name ?? 'Otros') as $category => $types)<optgroup label="{{ $category }}">@foreach($types as $type)<option value="{{ $type->id }}" @selected($selectedType?->id === $type->id)>{{ $type->name }}</option>@endforeach</optgroup>@endforeach</select></div><div class="col-md-3 align-self-end"><button class="btn btn-outline-primary w-100">Continuar</button></div></form></div></section>

@if($selectedType && $selectedType->variants->isNotEmpty() && !$selectedVariant)
<section class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h2 class="h5">2. Selecciona una variante</h2><p>Este trámite necesita una variante aplicable. Si requiere evaluación guiada, selecciónala desde su ficha pública.</p><div class="d-flex flex-wrap gap-2">@foreach($selectedType->variants as $variant)@if(empty($variant->conditions))<a class="btn btn-outline-primary" href="{{ route('applicant.procedure-requests.create', ['tipo'=>$selectedType->id,'variante'=>$variant->code]) }}">{{ $variant->name }}</a>@endif @endforeach<a class="btn btn-primary" href="{{ route('catalog.show', $selectedType->code) }}">Abrir selector guiado</a></div></div></section>
@endif

@if($selectedType && ($selectedType->variants->isEmpty() || $selectedVariant))
<section class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><span class="section-eyebrow">Resumen previo</span><h2 class="h4 mt-2">{{ $selectedType->name }}@if($selectedVariant) — {{ $selectedVariant->name }}@endif</h2><p>{{ $selectedType->description }}</p><dl class="row mb-0"><dt class="col-sm-3">Modalidad</dt><dd class="col-sm-9">{{ $selectedVariant?->presentationModality?->name ?? $selectedType->presentationModality?->name ?? 'Por confirmar' }}</dd><dt class="col-sm-3">Monto</dt><dd class="col-sm-9">@php($priced=$selectedVariant ?? $selectedType){{ $priced->requires_payment ? $priced->currency.' '.$priced->amount : 'Sin pago configurado' }}</dd><dt class="col-sm-3">Instrucciones</dt><dd class="col-sm-9">{{ $selectedType->instructions ?: 'Sin instrucciones adicionales.' }}</dd></dl></div></section>

<form method="POST" action="{{ route('applicant.procedure-requests.store') }}" enctype="multipart/form-data" data-requires-online data-confirm-submit="¿Confirmas el envío definitivo de esta solicitud?" novalidate>@csrf
<input type="hidden" name="procedure_type_id" value="{{ $selectedType->id }}">@if($selectedVariant)<input type="hidden" name="procedure_variant_id" value="{{ $selectedVariant->id }}">@endif
@foreach($eligibility as $key=>$value)<input type="hidden" name="eligibility[{{ $key }}]" value="{{ is_scalar($value) ? $value : '' }}">@endforeach
<section class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h2 class="h4">Datos de la solicitud</h2><div class="mb-3"><label class="form-label" for="subject">Asunto</label><input class="form-control @error('subject') is-invalid @enderror" id="subject" name="subject" value="{{ old('subject') }}" maxlength="200" required>@error('subject')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="mb-3"><label class="form-label" for="description">Descripción</label><textarea class="form-control @error('description') is-invalid @enderror" id="description" name="description" rows="4" maxlength="5000" required>{{ old('description') }}</textarea>@error('description')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
@foreach($fields as $field)@php($name='responses['.$field->key.']')@php($value=old('responses.'.$field->key))<div class="mb-3"><label class="form-label" for="field-{{ $field->key }}">{{ $field->label }}@if($field->required)<span aria-hidden="true"> *</span><span class="visually-hidden"> (obligatorio)</span>@endif</label>
@if($field->type->value==='textarea')<textarea class="form-control" id="field-{{ $field->key }}" name="{{ $name }}" @required($field->required)>{{ $value }}</textarea>
@elseif(in_array($field->type->value,['select','semester','shift','career']))<select class="form-select" id="field-{{ $field->key }}" name="{{ $name }}" @required($field->required)><option value="">Selecciona</option>@foreach($forms->options($field) as $option=>$label)<option value="{{ $option }}" @selected((string)$value===(string)$option)>{{ $label }}</option>@endforeach</select>
@elseif(in_array($field->type->value,['multiselect','course_units']))<select class="form-select" id="field-{{ $field->key }}" name="responses[{{ $field->key }}][]" multiple @required($field->required)>@foreach($forms->options($field) as $option=>$label)<option value="{{ $option }}" @selected(in_array((string)$option,(array)$value,true))>{{ $label }}</option>@endforeach</select>
@elseif($field->type->value==='checkbox')<div class="form-check"><input type="hidden" name="{{ $name }}" value="0"><input class="form-check-input" id="field-{{ $field->key }}" name="{{ $name }}" type="checkbox" value="1" @checked($value)><label class="form-check-label" for="field-{{ $field->key }}">Sí</label></div>
@else<input class="form-control" id="field-{{ $field->key }}" name="{{ $name }}" type="{{ match($field->type->value){'email'=>'email','number'=>'number','date'=>'date','phone'=>'tel',default=>'text'} }}" value="{{ $value }}" @required($field->required)>@endif
@if($field->help_text)<div class="form-text" id="field-{{ $field->key }}-help">{{ $field->help_text }}</div>@endif @error('responses.'.$field->key)<div class="text-danger small" role="alert">{{ $message }}</div>@enderror</div>@endforeach</div></section>

<section class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h2 class="h4">Documentos y entrega física</h2><p class="small text-secondary">Los archivos se almacenan de forma privada. Máximo global: cinco archivos y 5 MB por archivo.</p>@forelse($requirements as $requirement)<div class="border rounded p-3 mb-3"><div class="d-flex justify-content-between"><strong>{{ $requirement->name }}</strong><span>{{ $requirement->required ? 'Obligatorio' : 'Opcional' }}</span></div><p class="small mb-2">{{ $requirement->description }}</p>@if($requirement->requires_physical_submission)<div class="alert alert-warning py-2">Presentar posteriormente: {{ $requirement->requires_original ? 'original' : 'copia' }}, {{ $requirement->copy_count }} ejemplar(es)@if($requirement->validity_value), vigencia {{ $requirement->validity_value }} {{ $requirement->validity_unit?->value }}@endif.</div>@endif @if($requirement->requires_digital_file)<label class="form-label" for="document-{{ $requirement->id }}">Copia digital {{ $requirement->required ? '(obligatoria)' : '(opcional)' }}</label><input class="form-control @error('documents.'.$requirement->id) is-invalid @enderror" id="document-{{ $requirement->id }}" name="documents[{{ $requirement->id }}]" type="file" @required($requirement->required)>@error('documents.'.$requirement->id)<div class="invalid-feedback">{{ $message }}</div>@enderror @endif</div>@empty<div class="mb-3"><label class="form-label" for="document-general">Documento general</label><input class="form-control" id="document-general" name="documents[general]" type="file" required></div>@endforelse</div></section>
<section class="card border-0 shadow-sm"><div class="card-body p-4"><h2 class="h4">Resumen y confirmación</h2><p>Se registrarán el trámite, la variante, las respuestas, los requisitos aplicados, el monto y la modalidad como snapshot histórico.</p><div class="form-check mb-3"><input class="form-check-input" id="confirmation" name="confirmation" type="checkbox" value="1" required><label class="form-check-label" for="confirmation">Confirmo que revisé el resumen y autorizo el envío.</label>@error('confirmation')<div class="text-danger small">{{ $message }}</div>@enderror</div><button class="btn btn-primary" type="submit">Confirmar y enviar solicitud</button></div></section></form>
@endif
@endsection
