@extends('layouts.authenticated')
@section('title',$procedureRequest->tracking_code)
@section('content')
<header class="d-flex flex-column flex-md-row justify-content-between gap-3 mb-4"><div><a class="small" href="{{ route('applicant.procedure-requests.index') }}">← Mis trámites</a><span class="section-eyebrow d-block mt-2">Código de seguimiento</span><h1 class="h2"><code>{{ $procedureRequest->tracking_code }}</code></h1><span class="badge text-bg-primary"><span aria-hidden="true">●</span> {{ $procedureRequest->status->name }}</span><p class="mt-2 mb-0 fw-semibold">Estado actual: {{ $procedureRequest->status->name }}</p></div></header>
<p class="lead">{{ $procedureRequest->subject }}</p>
@if($procedureRequest->titleProcess)<div class="alert alert-info"><strong>Etapa de titulación:</strong> {{ $procedureRequest->titleProcess->current_stage->label() }} <a class="btn btn-sm btn-outline-primary ms-2" href="{{ route('title-processes.show',$procedureRequest->titleProcess) }}">Ver proceso</a></div>@endif
@if($procedureRequest->academic_file_number)<div class="alert alert-success"><strong>Expediente académico o externo:</strong> {{ $procedureRequest->academic_file_number }}@if(data_get($procedureRequest->configuration_snapshot,'continuation_department'))<div><strong>Dependencia de continuación:</strong> {{ data_get($procedureRequest->configuration_snapshot,'continuation_department') }}</div>@endif</div>@endif
@if(data_get($procedureRequest->configuration_snapshot,'physical_submission.required'))<div class="alert alert-info"><strong>Pendiente de confirmación de entrega física.</strong>@if(data_get($procedureRequest->configuration_snapshot,'physical_submission.location'))<div>Lugar: {{ data_get($procedureRequest->configuration_snapshot,'physical_submission.location') }}</div>@endif @if(data_get($procedureRequest->configuration_snapshot,'physical_submission.schedule'))<div>Horario: {{ data_get($procedureRequest->configuration_snapshot,'physical_submission.schedule') }}</div>@endif</div>@endif
<section class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5">Resumen del trámite</h2><dl class="row mb-0"><dt class="col-sm-4">Trámite</dt><dd class="col-sm-8">{{ data_get($procedureRequest->configuration_snapshot,'procedure.name',$procedureRequest->procedureType->name) }}</dd><dt class="col-sm-4">Variante</dt><dd class="col-sm-8">{{ data_get($procedureRequest->configuration_snapshot,'variant.name',$procedureRequest->variant?->name ?? 'No aplica') }}</dd><dt class="col-sm-4">Modalidad</dt><dd class="col-sm-8">{{ data_get($procedureRequest->configuration_snapshot,'modality','No registrada') }}</dd><dt class="col-sm-4">Presentación</dt><dd class="col-sm-8">{{ $procedureRequest->submitted_at->format('d/m/Y H:i') }}</dd><dt class="col-sm-4">Estado actual</dt><dd class="col-sm-8">{{ $procedureRequest->status->name }}</dd></dl>@if(data_get($procedureRequest->configuration_snapshot,'physical_submission.pending_originals'))<div class="alert alert-warning mt-3 mb-0"><strong>Documentación física pendiente</strong><ul class="mb-0">@foreach(data_get($procedureRequest->configuration_snapshot,'physical_submission.pending_originals',[]) as $item)<li>{{ $item['name'] }} — {{ $item['original']?'original':'copia' }}, {{ $item['copies'] }} ejemplar(es)</li>@endforeach</ul></div>@endif</div></section>
<div class="row g-4"><div class="col-xl-8"><section class="card border-0 shadow-sm" aria-labelledby="timeline-title"><div class="card-body p-4"><h2 class="h4" id="timeline-title">Línea de tiempo</h2><p class="text-secondary">Eventos oficiales ordenados cronológicamente.</p><ol class="timeline list-unstyled mb-0">@forelse($timelineEvents as $event)<li class="timeline-item" tabindex="0"><div class="d-flex flex-wrap gap-2 align-items-center"><span aria-hidden="true">{{ $event['icon'] }}</span><strong>{{ $event['title'] }}</strong>@if($event['status'])<span class="badge text-bg-light border text-dark">{{ $event['status'] }}</span>@endif</div>@if($event['description'])<p class="mb-1">{{ $event['description'] }}</p>@endif @foreach($event['details'] as $label=>$value)<div class="small"><strong>{{ $label }}:</strong> {{ $value }}</div>@endforeach<time class="small text-secondary" datetime="{{ $event['occurred_at']->toIso8601String() }}">{{ $event['occurred_at']->format('d/m/Y H:i') }}</time></li>@empty<li>No hay eventos registrados.</li>@endforelse</ol></div></section></div>
<div class="col-xl-4"><section class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5">Documentos digitales</h2>@forelse($procedureRequest->documents as $document)<div class="border-bottom py-2"><strong>{{ $document->requirement?->name ?? 'Documento adicional' }}</strong><a class="btn btn-sm btn-outline-primary d-block mt-1" href="{{ route('applicant.procedure-requests.documents.download',[$procedureRequest,$document]) }}">Descargar</a></div>@empty<p class="text-secondary">No hay archivos digitales.</p>@endforelse</div></section>@if($procedureRequest->response)<section class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5">Respuesta</h2><p>{{ $procedureRequest->response->summary }}</p><a class="btn btn-primary" href="{{ route('applicant.procedure-requests.response.download',$procedureRequest) }}">Descargar respuesta</a></div></section>@endif<section class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5">Notificaciones</h2>@forelse($relatedNotifications as $notification)<div class="border-bottom py-2"><p class="mb-1">{{ $notification->data['message'] }}</p><small>{{ $notification->created_at->format('d/m/Y H:i') }}</small></div>@empty<p class="text-secondary">Sin notificaciones.</p>@endforelse</div></section></div></div>
@endsection
