@extends('layouts.authenticated')
@section('title','Comunicaciones '.$procedureRequest->tracking_code)
@section('content')
<div class="mb-4"><h1 class="h2">Comunicaciones del expediente</h1><p><code>{{ $procedureRequest->tracking_code }}</code> · {{ $procedureRequest->procedureType->name }} · {{ $procedureRequest->user->first_name }} {{ $procedureRequest->user->last_name }}</p></div>
<div class="row g-4"><div class="col-xl-7">
<section class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5">Programar cita</h2><form method="POST" action="{{ route('communications.appointments.store',$procedureRequest) }}">@csrf<div class="row g-3"><div class="col-md-4"><label class="form-label">Fecha</label><input class="form-control" type="date" name="appointment_date" required></div><div class="col-md-4"><label class="form-label">Inicio</label><input class="form-control" type="time" name="starts_at" required></div><div class="col-md-4"><label class="form-label">Final</label><input class="form-control" type="time" name="ends_at" required></div><div class="col-md-6"><label class="form-label">Oficina</label><input class="form-control" name="office" required></div><div class="col-md-6"><label class="form-label">Área</label><select class="form-select" name="area_id"><option value="">Sin área</option>@foreach($areas as $area)<option value="{{ $area->id }}">{{ $area->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Persona de referencia</label><input class="form-control" name="reference_person"></div><div class="col-md-6"><label class="form-label">Fecha límite</label><input class="form-control" type="date" name="deadline"></div><div class="col-12"><label class="form-label">Motivo</label><input class="form-control" name="reason" required></div><div class="col-12"><label class="form-label">Instrucciones</label><textarea class="form-control" name="instructions"></textarea></div></div><button class="btn btn-primary mt-3">Programar</button></form></div></section>
@foreach($procedureRequest->appointments->sortByDesc('appointment_date') as $appointment)<section class="card border-0 shadow-sm mb-3"><div class="card-body"><strong>{{ $appointment->appointment_date->format('d/m/Y') }} {{ $appointment->starts_at }}–{{ $appointment->ends_at }}</strong><span class="badge text-bg-secondary">{{ $appointment->status }}</span><p>{{ $appointment->office }} · {{ $appointment->reason }}</p>@if(!in_array($appointment->status,['attended','cancelled','rescheduled']))<details><summary>Reprogramar</summary><form class="row g-2 mt-2" method="POST" action="{{ route('communications.appointments.reschedule',[$procedureRequest,$appointment]) }}">@csrf<div class="col"><input class="form-control" type="date" name="appointment_date" required></div><div class="col"><input class="form-control" type="time" name="starts_at" required></div><div class="col"><input class="form-control" type="time" name="ends_at" required></div><input type="hidden" name="office" value="{{ $appointment->office }}"><input type="hidden" name="reason" value="{{ $appointment->reason }}"><button class="btn btn-outline-primary">Reprogramar</button></form></details>@endif</div></section>@endforeach
<section class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5">Historial de notificaciones</h2>@forelse($notificationHistory as $notification)<div class="border-bottom py-2"><strong>{{ $notification->data['event'] }}</strong><p class="mb-0">{{ $notification->data['message'] }}</p><small>{{ $notification->created_at->format('d/m/Y H:i') }}</small></div>@empty<p>Sin notificaciones.</p>@endforelse</div></section>
</div><div class="col-xl-5">
<section class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5">Recojo</h2>@if(!$procedureRequest->pickup)<form method="POST" action="{{ route('communications.pickup.ready',$procedureRequest) }}">@csrf<label class="form-label">Disponible desde</label><input class="form-control mb-2" type="datetime-local" name="available_at" required><label class="form-label">Oficina</label><input class="form-control mb-2" name="office" required><label class="form-label">Requisito para recoger</label><input class="form-control mb-2" name="pickup_requirement"><label class="form-label">Observación</label><textarea class="form-control mb-2" name="observation"></textarea><button class="btn btn-success">Marcar listo</button></form>@elseif($procedureRequest->pickup->status==='ready')<p class="alert alert-success">Listo en {{ $procedureRequest->pickup->office }}</p><form method="POST" action="{{ route('communications.pickup.deliver',$procedureRequest) }}">@csrf<label class="form-label">Persona que recibe</label><input class="form-control mb-2" name="received_by_name" required><label class="form-label">Fecha y hora</label><input class="form-control mb-2" type="datetime-local" name="delivered_at" required><div class="form-check mb-2"><input class="form-check-input" id="verified" type="checkbox" name="identity_document_verified" value="1" required><label class="form-check-label" for="verified">Documento de identidad verificado (sin guardar copia)</label></div><textarea class="form-control mb-2" name="observation" placeholder="Observación"></textarea><button class="btn btn-primary">Registrar entrega</button></form>@else<p>Entregado el {{ $procedureRequest->pickup->delivered_at->format('d/m/Y H:i') }}.</p>@endif</div></section>
<section class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5">Crear notificación estructurada</h2><form method="POST" action="{{ route('communications.notify',$procedureRequest) }}">@csrf<label class="form-label">Tipo</label><select class="form-select mb-2" name="type">@foreach(['request_registered'=>'Solicitud registrada','physical_reception_confirmed'=>'Expediente físico recibido','physical_documents_incomplete'=>'Documentos incompletos','request_observed'=>'Observación','correction_submitted'=>'Subsanación recibida','request_validated'=>'Trámite aprobado','request_rejected'=>'Trámite rechazado','request_derived'=>'Trámite derivado','attention_started'=>'En atención','originals_required'=>'Presentación de originales','request_finalized'=>'Trámite finalizado'] as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select><label class="form-label">Mensaje sin datos sensibles</label><textarea class="form-control mb-2" name="message" required></textarea><button class="btn btn-outline-primary">Enviar</button></form></div></section>
</div></div>
@if($errors->any())<div class="alert alert-danger mt-4"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@endsection
