@extends('layouts.authenticated')

@section('title', 'Búsqueda de expedientes')

@section('content')
    <div class="mb-4"><span class="section-eyebrow">Consulta documentaria</span><h1 class="h2 mt-2 mb-2">Búsqueda de expedientes</h1><p class="text-secondary mb-0">Los resultados están limitados automáticamente al alcance de tu rol.</p></div>
    <section class="card border-0 shadow-sm mb-4" aria-labelledby="search-filters-title"><div class="card-body p-4"><h2 class="h5" id="search-filters-title">Filtros</h2><form method="GET" action="{{ route('search.index') }}" role="search"><div class="row g-3">
        <div class="col-md-4 col-xl-3"><label class="form-label" for="codigo">Código</label><input class="form-control" id="codigo" name="codigo" value="{{ $filters['codigo'] ?? '' }}"></div>
        <div class="col-md-4 col-xl-3"><label class="form-label" for="documento">Documento del solicitante</label><input class="form-control" id="documento" name="documento" value="{{ $filters['documento'] ?? '' }}"></div>
        <div class="col-md-4 col-xl-3"><label class="form-label" for="nombre">Nombre del solicitante</label><input class="form-control" id="nombre" name="nombre" value="{{ $filters['nombre'] ?? '' }}"></div>
        <div class="col-md-4 col-xl-3"><label class="form-label" for="estado">Estado</label><select class="form-select" id="estado" name="estado"><option value="">Todos</option>@foreach($statuses as $status)<option value="{{ $status->id }}" @selected(($filters['estado'] ?? null) == $status->id)>{{ $status->name }}</option>@endforeach</select></div>
        <div class="col-md-4 col-xl-3"><label class="form-label" for="tramite">Tipo de trámite</label><select class="form-select" id="tramite" name="tramite"><option value="">Todos</option>@foreach($procedureTypes as $type)<option value="{{ $type->id }}" @selected(($filters['tramite'] ?? null) == $type->id)>{{ $type->name }}</option>@endforeach</select></div>
        <div class="col-md-4 col-xl-3"><label class="form-label" for="area">Área actual</label><select class="form-select" id="area" name="area"><option value="">Todas</option>@foreach($areas as $area)<option value="{{ $area->id }}" @selected(($filters['area'] ?? null) == $area->id)>{{ $area->name }}</option>@endforeach</select></div>
        <div class="col-md-4 col-xl-3"><label class="form-label" for="responsable">Responsable de área</label><input class="form-control" id="responsable" name="responsable" value="{{ $filters['responsable'] ?? '' }}" placeholder="Nombre del responsable"></div>
        <div class="col-md-4 col-xl-3"><label class="form-label" for="desde">Desde</label><input class="form-control" id="desde" name="desde" type="date" value="{{ $filters['desde'] ?? '' }}"></div>
        <div class="col-md-4 col-xl-3"><label class="form-label" for="hasta">Hasta</label><input class="form-control" id="hasta" name="hasta" type="date" value="{{ $filters['hasta'] ?? '' }}"></div>
        <div class="col-md-4"><label class="form-label" for="carrera">Carrera</label><input class="form-control" id="carrera" name="carrera" value="{{ $filters['carrera'] ?? '' }}"></div>
        <div class="col-md-4"><label class="form-label" for="categoria">Categoría</label><select class="form-select" id="categoria" name="categoria"><option value="">Todas</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(($filters['categoria'] ?? null)==$category->id)>{{ $category->name }}</option>@endforeach</select></div>
        <div class="col-md-4"><label class="form-label" for="variante">Variante</label><select class="form-select" id="variante" name="variante"><option value="">Todas</option>@foreach($variants as $variant)<option value="{{ $variant->id }}" @selected(($filters['variante'] ?? null)==$variant->id)>{{ $variant->name }}</option>@endforeach</select></div>
        <div class="col-md-4"><label class="form-label" for="modalidad">Modalidad</label><select class="form-select" id="modalidad" name="modalidad"><option value="">Todas</option>@foreach($modalities as $modality)<option value="{{ $modality->code->value }}" @selected(($filters['modalidad'] ?? null)===$modality->code->value)>{{ $modality->name }}</option>@endforeach</select></div>
        <div class="col-md-4"><label class="form-label" for="etapa">Etapa</label><input class="form-control" id="etapa" name="etapa" value="{{ $filters['etapa'] ?? '' }}"></div>
        <div class="col-md-4"><label class="form-label" for="modalidad_titulacion">Modalidad de titulación</label><select class="form-select" id="modalidad_titulacion" name="modalidad_titulacion"><option value="">Todas</option><option value="application_work" @selected(($filters['modalidad_titulacion']??null)==='application_work')>Trabajo de aplicación</option><option value="professional_exam" @selected(($filters['modalidad_titulacion']??null)==='professional_exam')>Examen de suficiencia</option></select></div>
        <div class="col-12 d-flex flex-wrap gap-3"><label><input type="checkbox" name="entrega_fisica" value="1" @checked($filters['entrega_fisica']??false)> Pendiente físico</label><label><input type="checkbox" name="cita" value="1" @checked($filters['cita']??false)> Con cita</label><label><input type="checkbox" name="documento_listo" value="1" @checked($filters['documento_listo']??false)> Documento listo</label></div>
        <div class="col-12 d-flex gap-2"><button class="btn btn-primary" type="submit">Buscar</button><a class="btn btn-outline-secondary" href="{{ route('search.index') }}">Limpiar</a><a class="btn btn-outline-success" href="{{ route('search.export', request()->query()) }}">Exportar CSV</a></div>
    </div></form></div></section>

    <div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><caption class="visually-hidden">Resultados de expedientes</caption><thead><tr><th>Código</th><th>Solicitante</th><th>Trámite</th><th>Estado</th><th>Área actual</th><th>Fecha</th><th class="text-end">Acción</th></tr></thead><tbody>@forelse($procedureRequests as $item)<tr><td><code class="tracking-code">{{ $item->tracking_code }}</code></td><td>{{ $item->user->first_name }} {{ $item->user->last_name }}<small class="d-block text-secondary">{{ $item->user->document_type }} {{ $item->user->document_number }}</small></td><td>{{ $item->procedureType->name }}</td><td><span class="badge text-bg-primary">{{ $item->status->name }}</span></td><td>{{ $item->latestDerivation?->destinationArea?->name ?? 'Sin área' }}</td><td>{{ $item->submitted_at->format('d/m/Y') }}</td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="{{ route('search.show', $item) }}">Consultar</a></td></tr>@empty<tr><td colspan="7" class="text-center text-secondary py-5">No se encontraron expedientes.</td></tr>@endforelse</tbody></table></div>@if($procedureRequests->hasPages())<div class="card-footer bg-white">{{ $procedureRequests->links() }}</div>@endif</div>
@endsection
