@extends('layouts.authenticated')
@section('title', $item ? 'Editar configuración' : 'Crear configuración')
@section('content')
<x-admin.catalog-header :title="$item ? 'Editar configuración' : 'Crear configuración'" :description="'Trámite: '.$procedureType->name" />
@php($routeBase = 'admin.procedure-types.'.$kind)
<div class="card border-0 shadow-sm"><div class="card-body"><form method="POST" action="{{ $item ? route($routeBase.'.update', [$procedureType, $item]) : route($routeBase.'.store', $procedureType) }}" novalidate>@csrf @if($item) @method('PUT') @endif
@if($kind === 'variants')
 <div class="row"><div class="col-md-4 mb-3"><label class="form-label" for="code">Código</label><input class="form-control" id="code" name="code" value="{{ old('code', $item?->code) }}" required></div><div class="col-md-8 mb-3"><label class="form-label" for="name">Nombre</label><input class="form-control" id="name" name="name" value="{{ old('name', $item?->name) }}" required></div></div>
 <div class="mb-3"><label class="form-label" for="description">Descripción</label><textarea class="form-control" id="description" name="description">{{ old('description', $item?->description) }}</textarea></div>
 <div class="row"><div class="col-md-6 mb-3"><label class="form-label" for="presentation_modality_id">Modalidad</label><select class="form-select" name="presentation_modality_id"><option value="">Heredar del trámite</option>@foreach($modalities as $modality)<option value="{{ $modality->id }}" @selected(old('presentation_modality_id', $item?->presentation_modality_id)==$modality->id)>{{ $modality->name }}</option>@endforeach</select></div><div class="col-md-3 mb-3"><label class="form-label">Plazo (días)</label><input class="form-control" type="number" name="attention_days" value="{{ old('attention_days', $item?->attention_days) }}"></div><div class="col-md-3 mb-3"><label class="form-label">Orden</label><input class="form-control" type="number" name="sort_order" value="{{ old('sort_order', $item?->sort_order ?? 0) }}" required></div></div>
 @include('admin.nested-catalog._availability-payment')
 <fieldset class="border rounded p-3 mb-3"><legend class="h6">Presentación física</legend><div class="row"><div class="col-md-5"><label class="form-label">Lugar</label><input class="form-control" name="physical_submission_location" value="{{ old('physical_submission_location', $item?->physical_submission_location) }}"></div><div class="col-md-5"><label class="form-label">Horario</label><input class="form-control" name="physical_submission_schedule" value="{{ old('physical_submission_schedule', $item?->physical_submission_schedule) }}"></div><div class="col-md-2"><label class="form-label">Plazo (días)</label><input class="form-control" type="number" min="1" max="365" name="physical_submission_deadline_days" value="{{ old('physical_submission_deadline_days', $item?->physical_submission_deadline_days) }}"></div></div></fieldset>
 <div class="mb-3"><label class="form-label" for="conditions_json">Condiciones JSON</label><textarea class="form-control font-monospace" id="conditions_json" name="conditions_json" rows="4">{{ old('conditions_json', $item && $item->conditions ? json_encode($item->conditions, JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) : '') }}</textarea><div class="form-text">Lista de reglas con field, operator y value.</div></div>
@elseif($kind === 'dynamic-fields')
 <div class="row"><div class="col-md-4 mb-3"><label class="form-label">Clave</label><input class="form-control" name="key" value="{{ old('key', $item?->key) }}" required></div><div class="col-md-4 mb-3"><label class="form-label">Tipo</label><select class="form-select" name="type">@foreach($fieldTypes as $type)<option value="{{ $type->value }}" @selected(old('type', $item?->type?->value)===$type->value)>{{ $type->value }}</option>@endforeach</select></div><div class="col-md-4 mb-3"><label class="form-label">Variante</label><select class="form-select" name="procedure_variant_id"><option value="">General</option>@foreach($variants as $variant)<option value="{{ $variant->id }}" @selected(old('procedure_variant_id', $item?->procedure_variant_id)==$variant->id)>{{ $variant->name }}</option>@endforeach</select></div></div>
 <div class="mb-3"><label class="form-label">Etiqueta</label><input class="form-control" name="label" value="{{ old('label', $item?->label) }}" required></div><div class="mb-3"><label class="form-label">Ayuda</label><textarea class="form-control" name="help_text">{{ old('help_text', $item?->help_text) }}</textarea></div>
 <div class="row"><div class="col-md-3 mb-3"><label class="form-label">Longitud mínima</label><input class="form-control" type="number" name="min_length" value="{{ old('min_length', $item?->min_length) }}"></div><div class="col-md-3 mb-3"><label class="form-label">Longitud máxima</label><input class="form-control" type="number" name="max_length" value="{{ old('max_length', $item?->max_length) }}"></div><div class="col-md-3 mb-3"><label class="form-label">Valor mínimo</label><input class="form-control" type="number" step="any" name="min_value" value="{{ old('min_value', $item?->min_value) }}"></div><div class="col-md-3 mb-3"><label class="form-label">Valor máximo</label><input class="form-control" type="number" step="any" name="max_value" value="{{ old('max_value', $item?->max_value) }}"></div></div>
 <div class="mb-3"><label class="form-label">Opciones JSON</label><textarea class="form-control font-monospace" name="options_json">{{ old('options_json', $item?->options ? json_encode($item->options, JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) : '') }}</textarea></div><div class="mb-3"><label class="form-label">Reglas de validación</label><input class="form-control" name="validation_rule" value="{{ old('validation_rule', $item?->validation_rule) }}"></div><div class="mb-3"><label class="form-label">Condición de visibilidad JSON</label><textarea class="form-control font-monospace" name="visibility_conditions_json">{{ old('visibility_conditions_json', $item?->visibility_conditions ? json_encode($item->visibility_conditions, JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) : '') }}</textarea></div>
 <div class="row"><div class="col-md-4"><label class="form-label">Orden</label><input class="form-control" type="number" name="sort_order" value="{{ old('sort_order', $item?->sort_order ?? 0) }}"></div><div class="col-md-4 form-check mt-4"><input type="hidden" name="required" value="0"><input class="form-check-input" type="checkbox" name="required" value="1" @checked(old('required', $item?->required))><label class="form-check-label">Obligatorio</label></div></div>
@else
 <div class="row"><div class="col-md-6 mb-3"><label class="form-label">Nombre</label><input class="form-control" name="name" value="{{ old('name', $item?->name) }}" required></div><div class="col-md-6 mb-3"><label class="form-label">Tipo</label><select class="form-select" name="type">@foreach($prerequisiteTypes as $type)<option value="{{ $type->value }}" @selected(old('type', $item?->type?->value)===$type->value)>{{ $type->value }}</option>@endforeach</select></div></div>
 <div class="mb-3"><label class="form-label">Trámite anterior</label><select class="form-select" name="required_procedure_type_id"><option value="">No aplica</option>@foreach($procedureTypes as $type)<option value="{{ $type->id }}" @selected(old('required_procedure_type_id', $item?->required_procedure_type_id)==$type->id)>{{ $type->name }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Descripción/resultado requerido</label><textarea class="form-control" name="description">{{ old('description', $item?->description) }}</textarea></div><div class="mb-3"><label class="form-label">Condiciones JSON</label><textarea class="form-control font-monospace" name="conditions_json">{{ old('conditions_json', $item?->conditions ? json_encode($item->conditions, JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) : '') }}</textarea></div><input type="hidden" name="procedure_variant_id" value=""><input type="hidden" name="required" value="1"><div class="mb-3"><label class="form-label">Orden</label><input class="form-control" type="number" name="sort_order" value="{{ old('sort_order', $item?->sort_order ?? 0) }}"></div>
@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="d-flex gap-2 mt-4"><button class="btn btn-primary">Guardar</button><a class="btn btn-outline-secondary" href="{{ route($routeBase.'.index', $procedureType) }}">Cancelar</a></div></form></div></div>
@endsection
