@extends('layouts.authenticated')
@section('title', $title)
@section('content')
<div class="d-flex flex-column flex-md-row justify-content-between gap-3 mb-4"><div><nav aria-label="Ruta"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{ route('admin.procedure-types.index') }}">Trámites</a></li><li class="breadcrumb-item active">{{ $title }}</li></ol></nav><h1 class="h2">{{ $title }} de {{ $procedureType->name }}</h1></div><a class="btn btn-primary align-self-md-start" href="{{ route('admin.procedure-types.'.$kind.'.create', $procedureType) }}">Crear</a></div>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Orden</th><th>Configuración</th><th>Ámbito/Tipo</th><th>Estado</th><th class="text-end">Acciones</th></tr></thead><tbody>
@forelse($items as $item)<tr><td>{{ $item->sort_order }}</td><td><strong>{{ $item->name ?? $item->label }}</strong><small class="d-block text-secondary">{{ $item->description ?? $item->help_text }}</small></td><td>@if($kind === 'variants'){{ $item->presentationModality?->name ?? 'Hereda modalidad' }}@elseif($kind === 'dynamic-fields'){{ $item->type->value }} · {{ $item->variant?->name ?? 'General' }}@else{{ $item->type->value }} · {{ $item->requiredProcedureType?->name ?? 'Verificación' }}@endif</td><td><x-catalog-status :active="$item->active" /></td><td class="text-end"><div class="d-inline-flex gap-2"><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.procedure-types.'.$kind.'.edit', [$procedureType, $item]) }}">Editar</a><form method="POST" action="{{ route('admin.procedure-types.'.$kind.'.toggle', [$procedureType, $item]) }}" data-confirm-submit="¿Confirmas el cambio de estado?">@csrf @method('PATCH')<button class="btn btn-sm {{ $item->active ? 'btn-outline-danger' : 'btn-outline-success' }}">{{ $item->active ? 'Desactivar' : 'Activar' }}</button></form></div></td></tr>
@empty<tr><td colspan="5" class="text-center py-4">No hay registros configurados.</td></tr>@endforelse
</tbody></table></div>@if($items->hasPages())<div class="card-footer bg-white">{{ $items->links() }}</div>@endif</div>
@endsection
