@extends('layouts.authenticated')

@section('title', 'Auditoría')

@section('content')
    <div class="mb-4"><span class="section-eyebrow">Administración</span><h1 class="h2 mt-2 mb-2">Consulta de auditoría</h1><p class="text-secondary mb-0">Registro histórico de solo lectura. No contiene contraseñas, tokens ni contenido de archivos.</p></div>
    <section class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><form method="GET" action="{{ route('admin.audit-logs.index') }}" role="search"><div class="row g-3"><div class="col-md-4"><label class="form-label" for="usuario">Usuario</label><input class="form-control" id="usuario" name="usuario" value="{{ $filters['usuario'] ?? '' }}" placeholder="Nombre, documento o correo"></div><div class="col-md-4"><label class="form-label" for="accion">Acción</label><select class="form-select" id="accion" name="accion"><option value="">Todas</option>@foreach($actions as $action)<option value="{{ $action }}" @selected(($filters['accion'] ?? null) === $action)>{{ $presenter->action($action) }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label" for="entidad">Entidad</label><select class="form-select" id="entidad" name="entidad"><option value="">Todas</option>@foreach($entities as $class => $label)<option value="{{ $class }}" @selected(($filters['entidad'] ?? null) === $class)>{{ $label }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label" for="desde">Desde</label><input class="form-control" id="desde" name="desde" type="date" value="{{ $filters['desde'] ?? '' }}"></div><div class="col-md-3"><label class="form-label" for="hasta">Hasta</label><input class="form-control" id="hasta" name="hasta" type="date" value="{{ $filters['hasta'] ?? '' }}"></div><div class="col-12 d-flex gap-2"><button class="btn btn-primary" type="submit">Aplicar filtros</button><a class="btn btn-outline-secondary" href="{{ route('admin.audit-logs.index') }}">Limpiar</a></div></div></form></div></section>
    <div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><caption class="visually-hidden">Registros de auditoría</caption><thead><tr><th>Fecha</th><th>Usuario</th><th>Acción</th><th>Entidad</th><th>Información</th></tr></thead><tbody>@forelse($logs as $log)<tr><td>{{ $log->created_at->format('d/m/Y H:i') }}</td><td>{{ $log->user ? $log->user->first_name.' '.$log->user->last_name : 'Sistema' }}<small class="d-block text-secondary">{{ $log->user?->email }}</small></td><td>{{ $log->display_action }}</td><td>{{ $log->display_entity }} #{{ $log->auditable_id }}</td><td>@forelse($log->safe_details as $key => $value)<span class="d-block small"><strong>{{ str($key)->replace('_', ' ')->title() }}:</strong> {{ $value ?? 'Sin valor' }}</span>@empty<span class="text-secondary">Sin información adicional</span>@endforelse</td></tr>@empty<tr><td colspan="5" class="text-center text-secondary py-5">No existen registros con esos filtros.</td></tr>@endforelse</tbody></table></div>@if($logs->hasPages())<div class="card-footer bg-white">{{ $logs->links() }}</div>@endif</div>
@endsection
