@extends('layouts.authenticated')

@section('title', 'Reportes básicos')

@section('content')
    <div class="mb-4"><span class="section-eyebrow">Indicadores</span><h1 class="h2 mt-2 mb-2">Reportes básicos</h1><p class="text-secondary mb-0">Los indicadores respetan el mismo alcance documentario de tu rol.</p></div>
    <section class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><form method="GET" action="{{ route('reports.index') }}"><div class="row g-3 align-items-end"><div class="col-md-4"><label class="form-label" for="desde">Desde</label><input class="form-control" id="desde" name="desde" type="date" value="{{ $filters['desde'] ?? '' }}"></div><div class="col-md-4"><label class="form-label" for="hasta">Hasta</label><input class="form-control" id="hasta" name="hasta" type="date" value="{{ $filters['hasta'] ?? '' }}"></div><div class="col-md-4 d-flex gap-2"><button class="btn btn-primary" type="submit">Aplicar periodo</button><a class="btn btn-outline-secondary" href="{{ route('reports.index') }}">Limpiar</a></div></div></form></div></section>
    <div class="row g-4 mb-4"><div class="col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><span class="text-secondary">Total</span><strong class="display-6 d-block">{{ (int) ($report['summary']->total ?? 0) }}</strong></div></div></div><div class="col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><span class="text-secondary">Pendientes</span><strong class="display-6 d-block">{{ (int) ($report['summary']->pending ?? 0) }}</strong></div></div></div><div class="col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><span class="text-secondary">Atendidas o finalizadas</span><strong class="display-6 d-block">{{ (int) ($report['summary']->attended ?? 0) }}</strong></div></div></div></div>
    <div class="alert alert-light border"><strong>Tiempo promedio entre registro y respuesta:</strong> {{ $report['averageHours'] !== null ? number_format((float) $report['averageHours'], 1).' horas' : 'Sin datos suficientes' }}</div>
    <div class="row g-4">@foreach([['Solicitudes por estado', 'byStatus'], ['Solicitudes por tipo de trámite', 'byType'], ['Solicitudes por área', 'byArea'], ['Solicitudes por periodo', 'byPeriod']] as [$title, $key])<div class="col-xl-6"><section class="card border-0 shadow-sm h-100"><div class="card-body p-4"><h2 class="h5">{{ $title }}</h2><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>Categoría</th><th class="text-end">Cantidad</th></tr></thead><tbody>@forelse($report[$key] as $row)<tr><td>{{ $row->label }}</td><td class="text-end">{{ $row->total }}</td></tr>@empty<tr><td colspan="2" class="text-secondary">Sin datos.</td></tr>@endforelse</tbody></table></div></div></section></div>@endforeach</div>
    <section class="mt-4" aria-labelledby="extended-reports"><h2 class="h4" id="extended-reports">Indicadores ampliados</h2><div class="row g-3 mb-4"><div class="col-md-3"><div class="card"><div class="card-body">Pendientes físicos<strong class="d-block h3">{{ $report['pendingPhysical'] }}</strong></div></div></div><div class="col-md-3"><div class="card"><div class="card-body">Citas<strong class="d-block h3">{{ $report['appointments'] }}</strong></div></div></div><div class="col-md-3"><div class="card"><div class="card-body">Listos no recogidos<strong class="d-block h3">{{ $report['readyNotCollected'] }}</strong></div></div></div><div class="col-md-3"><div class="card"><div class="card-body">Convalidaciones<strong class="d-block h3">{{ $report['convalidations'] }}</strong></div></div></div></div>@foreach([['Solicitudes por categoría','byCategory'],['Solicitudes por modalidad','byModality'],['Solicitudes por carrera','byCareer'],['Titulación por modalidad','byTitleModality'],['Titulación por etapa','byTitleStage']] as [$title,$key])<div class="card mb-3"><div class="card-body"><h3 class="h5">{{ $title }}</h3><table class="table table-sm"><tbody>@forelse($report[$key] as $row)<tr><td>{{ $row->label }}</td><td class="text-end">{{ $row->total }}</td></tr>@empty<tr><td>Sin datos.</td></tr>@endforelse</tbody></table></div></div>@endforeach</section>
@endsection
