@extends('layouts.authenticated')

@section('title', 'Cierre de expedientes')

@section('content')
    <div class="mb-4"><span class="section-eyebrow">Mesa de Partes</span><h1 class="h2 mt-2 mb-2">Cierre de expedientes</h1><p class="text-secondary mb-0">Revisa las respuestas emitidas antes de finalizar los trámites.</p></div>
    <section class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><form method="GET" action="{{ route('front-desk.closures.index') }}" role="search"><div class="row g-3 align-items-end"><div class="col-md-6"><label class="form-label" for="codigo">Código de seguimiento</label><input class="form-control" id="codigo" name="codigo" value="{{ $filters['codigo'] ?? '' }}"></div><div class="col-md-6 d-flex gap-2"><button class="btn btn-primary" type="submit">Buscar</button><a class="btn btn-outline-secondary" href="{{ route('front-desk.closures.index') }}">Limpiar</a></div></div></form></div></section>
    <div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><caption class="visually-hidden">Expedientes atendidos o finalizados</caption><thead><tr><th>Código</th><th>Trámite</th><th>Área autora</th><th>Estado</th><th class="text-end">Acción</th></tr></thead><tbody>@forelse($procedureRequests as $item)<tr><td><code class="tracking-code">{{ $item->tracking_code }}</code></td><td>{{ $item->procedureType->name }}<small class="d-block text-secondary">{{ $item->subject }}</small></td><td>{{ $item->response?->author?->area?->name ?? 'Sin área identificada' }}</td><td><span class="badge text-bg-primary">{{ $item->status->name }}</span></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="{{ route('front-desk.closures.show', $item) }}">Revisar respuesta</a></td></tr>@empty<tr><td colspan="5" class="text-center text-secondary py-5">No hay expedientes pendientes o cerrados.</td></tr>@endforelse</tbody></table></div>@if($procedureRequests->hasPages())<div class="card-footer bg-white">{{ $procedureRequests->links() }}</div>@endif</div>
@endsection
