<?php

$field = fn (string $key, string $label, string $type = 'text') => compact('key', 'label', 'type') + ['required' => true];
$requirement = fn (string $name, array $extra = []) => array_replace(compact('name') + ['type' => 'digital_file', 'required' => true, 'requires_digital_file' => true, 'requires_physical_submission' => false, 'allowed_formats' => ['pdf'], 'max_file_size_kb' => 5120], $extra);
$procedure = fn (string $code, string $name, array $fields, array $requirements, array $extra = []) => array_replace(compact('code', 'name', 'fields', 'requirements') + ['description' => 'Trámite institucional publicado. Las condiciones académicas declaradas requieren verificación del instituto.', 'active' => true, 'reception_open' => true, 'allows_digital_registration' => true, 'requires_physical_delivery' => false], $extra);
$personal = [$field('carrera', 'Carrera', 'career'), $field('turno', 'Turno', 'shift')];
$signed = $requirement('Solicitud firmada');
$dni = $requirement('Copia simple de DNI', ['requires_simple_copy' => true]);

return [
    'version' => '2026.07.3',
    'modalities' => [
        ['code' => 'hybrid', 'name' => 'Híbrida', 'description' => 'Registro digital con presentación posterior de originales.', 'active' => true],
    ],
    'categories' => [
        ['code' => 'ESTUDIANTES_REGULARES', 'name' => 'Estudiantes regulares', 'sort_order' => 10],
        ['code' => 'EGRESADOS', 'name' => 'Egresados', 'sort_order' => 20],
        ['code' => 'CONVALIDACIONES', 'name' => 'Convalidaciones de estudios', 'sort_order' => 30],
        ['code' => 'TITULACION', 'name' => 'Titulación', 'sort_order' => 40],
    ],
    'procedures' => [
        'ESTUDIANTES_REGULARES' => [
            $procedure('REG_CONSTANCIA_ESTUDIOS', 'Constancia de estudios', [...$personal, $field('semestre', 'Semestre', 'semester')], [$requirement('Solicitud con datos personales y de estudios'), $requirement('Constancia de registro de matrícula del semestre vigente'), $requirement('Voucher de pago de matrícula'), $dni, $requirement('Voucher de pago de derecho')], ['requires_payment' => true, 'amount' => 20, 'payment_concept' => 'Derecho de constancia de estudios', 'instructions' => 'Condición declarada: matrícula vigente; su verificación corresponde al instituto.']),
            $procedure('REG_REPORTE_NOTAS', 'Reporte de notas', [...$personal, $field('anios_estudio', 'Años de estudio', 'year')], [$signed, $requirement('Voucher o recibo de pago'), $dni], ['requires_payment' => true, 'amount' => 5, 'instructions' => 'Aplicable a ingresantes desde 2007, sujeto a verificación institucional.']),
            $procedure('REG_RESERVA_MATRICULA', 'Reserva de matrícula', [$field('motivo', 'Motivo', 'textarea')], [$requirement('Solicitud simple indicando motivo'), $requirement('Constancia de registro de matrícula vigente'), $requirement('Certificado original de trabajo o salud según motivo', ['requires_original' => true, 'requires_physical_submission' => true, 'sensitive' => true]), $requirement('Voucher o recibo de pago de matrícula'), $dni], ['instructions' => 'Plazo configurable. La fuente menciona hasta un mes desde el inicio del cronograma.']),
            $procedure('REG_LICENCIA_ESTUDIOS', 'Licencia de estudios', [$field('motivo', 'Motivo', 'textarea')], [$signed, $requirement('Constancia de registro de matrícula'), $requirement('Voucher o recibo de matrícula'), $requirement('Certificado original de trabajo o salud', ['requires_original' => true, 'requires_physical_submission' => true, 'sensitive' => true]), $dni], ['instructions' => 'Hasta un mes antes de finalizar el semestre; posteriormente solo con sustento médico, sujeto a verificación.']),
            $procedure('REG_RANKING_NOTAS', 'Ranking de notas', [], [$signed, $requirement('Voucher o recibo de pago de matrícula'), $dni]),
            $procedure('REG_REINGRESO', 'Reingreso', [...$personal, $field('semestre_anios', 'Semestre o años estudiados')], [$signed, $requirement('Reporte de notas'), $dni], ['instructions' => 'Declarar no más de dos años de interrupción. La matrícula posterior al dictamen corresponde a Secretaría Académica.']),
            $procedure('REG_CAMBIO_CARRERA', 'Cambio interno de carrera', [$field('carrera_actual', 'Carrera actual', 'career'), $field('carrera_solicitada', 'Carrera solicitada', 'career'), $field('turno', 'Turno', 'shift'), $field('semestre', 'Semestre', 'semester'), $field('anios_estudio', 'Años estudiados', 'year')], [$signed, $requirement('Reporte de notas'), $dni], ['instructions' => 'Requiere primer periodo culminado, vacante, condición de invicto y no abandono; verificación institucional pendiente.']),
            $procedure('REG_CAMBIO_TURNO', 'Cambio de turno', [$field('turno_actual', 'Turno actual', 'shift'), $field('turno_solicitado', 'Turno solicitado', 'shift'), $field('motivo', 'Motivo', 'textarea'), $field('carrera', 'Carrera', 'career'), $field('semestre', 'Semestre', 'semester')], [$signed, $requirement('Certificado de trabajo, salud o recibos de servicios según motivo', ['sensitive' => true]), $requirement('Reporte de notas'), $dni]),
            $procedure('REG_TRASLADO_EXTERNO', 'Traslado externo', [...$personal, $field('semestre_solicitado', 'Semestre solicitado', 'semester'), $field('institucion_procedencia', 'Institución de procedencia')], [$signed, $requirement('Reporte o constancia de notas'), $dni], ['instructions' => 'Requiere misma carrera, condición de invicto y vacante, sujetas a verificación.', 'variants' => [
                ['code' => 'SOLICITUD_VACANTE', 'name' => 'Etapa 1: solicitud de vacante', 'requirements' => []],
                ['code' => 'DOCUMENTOS_VACANTE', 'name' => 'Etapa 2: documentos después de obtener vacante', 'requires_physical_delivery' => true, 'requirements' => [
                    $requirement('Partida de nacimiento original vigente', ['type' => 'physical_document', 'requires_original' => true, 'requires_physical_submission' => true, 'requires_digital_file' => false]),
                    $requirement('Certificados originales de educación secundaria del primero al quinto', ['type' => 'physical_document', 'requires_original' => true, 'requires_physical_submission' => true, 'requires_digital_file' => false]),
                    $requirement('Copia simple de DNI (etapa 2)', ['requires_simple_copy' => true]), $requirement('Certificado original de estudios superiores', ['type' => 'physical_document', 'requires_original' => true, 'requires_physical_submission' => true]),
                    $requirement('Resolución directoral de autorización de traslado'), $requirement('Pago de derechos', ['type' => 'payment']), $requirement('Visado si los certificados provienen de fuera de Arequipa', ['requires_endorsement' => true]),
                ]],
            ]]),
            $procedure('REG_EXONERACION_PRIMER_PUESTO', 'Exoneración de matrícula por primer puesto', [...$personal, $field('semestre', 'Semestre', 'semester'), $field('celular', 'Celular', 'phone'), $field('correo', 'Correo', 'email')], [$signed, $requirement('Ranking que acredite el primer puesto'), $dni], ['instructions' => 'Primer puesto del semestre anterior, sujeto a verificación. Genera resolución directoral.']),
            $procedure('REG_CAMBIO_NOMBRES', 'Cambio de apellidos o nombres', [$field('datos_anteriores', 'Datos anteriores'), $field('datos_nuevos', 'Datos nuevos'), ...$personal, $field('anios_estudio', 'Años de estudio', 'year'), $field('celular', 'Celular', 'phone'), $field('correo', 'Correo', 'email')], [$signed, $requirement('DNI actualizado', ['sensitive' => true]), $requirement('Partida de nacimiento rectificada', ['sensitive' => true]), $requirement('Sentencia judicial', ['sensitive' => true]), $requirement('Recibo de pago', ['type' => 'payment'])], ['instructions' => 'El resultado es una resolución directoral. También disponible para egresados.']),
            $procedure('REG_CARTA_PRACTICAS', 'Carta para prácticas profesionales', [...$personal, $field('anios_estudio', 'Años de estudio', 'year'), $field('celular', 'Celular', 'phone'), $field('correo', 'Correo', 'email'), $field('destinatario', 'Nombre del destinatario'), $field('cargo', 'Cargo'), $field('empresa', 'Empresa o institución'), $field('direccion', 'Dirección'), $field('area_practicas', 'Área de prácticas'), $field('fecha_inicio', 'Fecha de inicio', 'date'), $field('fecha_fin', 'Fecha de término', 'date')], [$signed, $requirement('Reporte de notas'), $dni, $requirement('Recibo de pago', ['type' => 'payment'])], ['requires_payment' => true, 'amount' => 5]),
        ],
        'EGRESADOS' => [
            $procedure('EGR_CONSTANCIA_EGRESADO', 'Constancia de egresado', [...$personal, $field('anios_estudio', 'Años de estudio', 'year'), $field('celular', 'Celular', 'phone'), $field('correo', 'Correo', 'email')], [$signed, $requirement('Reporte de notas invicto'), $requirement('Constancia de prácticas'), $dni, $requirement('Pago de derecho', ['type' => 'payment'])], ['requires_payment' => true, 'amount' => 20, 'instructions' => 'Orientación actual al sistema modular; esta condición es configurable y requiere verificación.']),
            $procedure('EGR_CONSTANCIA_BIBLIOTECA', 'Constancia de biblioteca', [], [$signed, $dni, $requirement('Pago de derecho', ['type' => 'payment'])], ['requires_payment' => true, 'amount' => 20, 'instructions' => 'Vigencia: 30 días.']),
            $procedure('EGR_CONSTANCIA_INSTITUCION', 'Constancia de la institución', [], [$signed, $dni, $requirement('Pago de derecho', ['type' => 'payment'])], ['requires_payment' => true, 'amount' => 20]),
            $procedure('EGR_PRIMERA_MATRICULA', 'Constancia de primera matrícula', [], [$requirement('Solicitud firmada con datos personales y de estudio'), $dni, $requirement('Pago de derecho', ['type' => 'payment'])], ['requires_payment' => true, 'amount' => 20]),
            $procedure('EGR_EVALUACION_EXTRAORDINARIA', 'Evaluación extraordinaria', [...$personal, $field('anios_estudio', 'Años de estudio', 'year'), $field('unidad_didactica', 'Unidad didáctica', 'course_units'), $field('nota_desaprobatoria', 'Nota desaprobatoria', 'number'), $field('anio_egreso', 'Año de egreso', 'year')], [$signed, $requirement('Reporte de notas'), $dni, $requirement('Recibo', ['type' => 'payment'])], ['instructions' => 'Disponible hasta tres años anteriores al actual, sujeto a verificación.', 'variants' => [
                ['code' => 'NOTA_10_12', 'name' => 'Nota de 10 a 12', 'requires_payment' => true, 'amount' => 120, 'conditions' => [['field' => 'nota_desaprobatoria', 'operator' => 'between', 'value' => [10, 12]]]],
                ['code' => 'NOTA_MENOR_10', 'name' => 'Nota menor de 10', 'requires_payment' => true, 'amount' => 150, 'conditions' => [['field' => 'nota_desaprobatoria', 'operator' => 'less_than', 'value' => 10]]],
            ]]),
            $procedure('EGR_SILABOS', 'Sílabos', [...$personal, $field('anios_estudio', 'Años de estudio', 'year'), $field('periodos_unidades', 'Periodos o unidades didácticas solicitadas', 'course_units')], [$signed, $dni, $requirement('Reporte de notas'), $requirement('Pago de derecho', ['type' => 'payment'])], ['requires_payment' => true, 'amount' => 25, 'instructions' => 'Disponibilidad de archivos desde el año 2000.']),
            $procedure('EGR_CARTA_PRACTICAS', 'Carta de presentación para prácticas', [...$personal, $field('anios_estudio', 'Años de estudio', 'year'), $field('celular', 'Celular', 'phone'), $field('correo', 'Correo', 'email'), $field('destinatario', 'Nombre del destinatario'), $field('cargo', 'Cargo'), $field('empresa', 'Empresa o institución'), $field('direccion', 'Dirección'), $field('area_practicas', 'Área de prácticas'), $field('fecha_inicio', 'Fecha de inicio', 'date'), $field('fecha_fin', 'Fecha de término', 'date')], [$signed, $requirement('Reporte de notas que acredite conclusión e invicto'), $dni, $requirement('Pago de derecho', ['type' => 'payment'])], ['requires_payment' => true, 'amount' => 5]),
        ],
        'CONVALIDACIONES' => [
            $procedure('CONV_CONSTANCIA_NOTAS', 'Constancia de notas para convalidación', [$field('estudios_anteriores', 'Datos de estudios anteriores', 'textarea'), $field('anio_ingreso', 'Año de ingreso', 'year') + ['min_value' => 1986, 'max_value' => 2006], $field('celular', 'Celular', 'phone'), $field('correo', 'Correo', 'email'), $field('semestre_solicitado', 'Semestre solicitado', 'semester'), $field('periodo_academico', 'Periodo académico')], [$signed, $requirement('Voucher o recibo de pago en caja', ['type' => 'payment']), $dni], ['requires_payment' => true, 'amount' => 20, 'reception_open' => false, 'unavailable_message' => 'La recepción se habilitará en las fechas programadas.', 'instructions' => 'Para antiguos estudiantes ingresantes de 1986 a 2006. Se emite por un semestre y solo es válida para el semestre solicitado. La disponibilidad y las fechas son configurables.']),
            $procedure('CONV_REPORTE_NOTAS', 'Reporte de notas para convalidación', [$field('estudios_anteriores', 'Datos de estudios anteriores', 'textarea'), $field('anio_ingreso', 'Año de ingreso', 'year') + ['min_value' => 2007], $field('celular', 'Celular', 'phone'), $field('correo', 'Correo', 'email'), $field('periodo_academico', 'Periodo académico')], [$signed, $requirement('Pago en caja', ['type' => 'payment']), $dni], ['requires_payment' => true, 'amount' => 5, 'attention_days' => 3, 'reception_open' => false, 'unavailable_message' => 'La recepción se habilitará en las fechas programadas.', 'instructions' => 'Para antiguos estudiantes ingresantes desde 2007. Plazo informativo configurable de hasta tres días.']),
            $procedure('CONV_INTERNA', 'Convalidación interna', [$field('carrera_actual', 'Carrera actual', 'career'), $field('semestre', 'Semestre', 'semester'), $field('turno', 'Turno', 'shift'), $field('unidades_didacticas', 'Unidades didácticas solicitadas', 'course_units'), $field('celular', 'Celular', 'phone'), $field('correo', 'Correo', 'email'), $field('anio_ingreso_anterior', 'Año de ingreso anterior', 'year'), $field('periodo_academico', 'Periodo académico')], [$signed, $requirement('Constancia o reporte de notas para convalidación'), $dni, $requirement('Pago en caja', ['type' => 'payment'])], ['requires_payment' => true, 'amount' => 50, 'reception_open' => false, 'unavailable_message' => 'La recepción se habilitará en las fechas programadas.', 'instructions' => 'Requiere validación previa de matrícula. La verificación académica corresponde al instituto. El pago se realiza en caja.', 'prerequisites' => [
                ['key' => 'matricula_validada', 'type' => 'administrative_verification', 'name' => 'Validación de matrícula', 'description' => 'La matrícula debe ser validada previamente por el instituto.'],
                ['key' => 'notas_1986_2006', 'type' => 'approved_procedure', 'required_procedure_code' => 'CONV_CONSTANCIA_NOTAS', 'name' => 'Constancia de notas previa', 'description' => 'Para ingresos de 1986 a 2006.', 'conditions' => [['field' => 'anio_ingreso_anterior', 'operator' => 'between', 'value' => [1986, 2006]]]],
                ['key' => 'notas_2007', 'type' => 'approved_procedure', 'required_procedure_code' => 'CONV_REPORTE_NOTAS', 'name' => 'Reporte de notas previo', 'description' => 'Para ingresos desde 2007.', 'conditions' => [['field' => 'anio_ingreso_anterior', 'operator' => 'greater_than_or_equal', 'value' => 2007]]],
            ]]),
            $procedure('CONV_EXTERNA', 'Convalidación externa', [$field('carrera_actual', 'Carrera actual', 'career'), $field('semestre', 'Semestre', 'semester'), $field('turno', 'Turno', 'shift'), $field('unidades_didacticas', 'Unidades didácticas solicitadas', 'course_units'), $field('institucion_procedencia', 'Institución de procedencia'), $field('tipo_institucion', 'Tipo de institución', 'select') + ['options' => ['instituto' => 'Instituto', 'universidad' => 'Universidad']], $field('celular', 'Celular', 'phone'), $field('correo', 'Correo', 'email'), $field('periodo_academico', 'Periodo académico')], [$signed, $requirement('Certificados originales de estudios', ['requires_original' => true, 'requires_physical_submission' => true, 'requires_digital_file' => true, 'sensitive' => true]), $requirement('Sílabos visados de las unidades a convalidar', ['requires_endorsement' => true, 'requires_physical_submission' => true, 'requires_digital_file' => true, 'sensitive' => true]), $dni, $requirement('Pago en caja', ['type' => 'payment'])], ['presentation_modality_code' => 'hybrid', 'requires_payment' => true, 'amount' => 60, 'requires_physical_delivery' => true, 'reception_open' => false, 'unavailable_message' => 'La recepción se habilitará en las fechas programadas.', 'instructions' => 'Modalidad híbrida. Adjunta copias digitales y presenta posteriormente los originales. Requiere validación previa de matrícula. El pago se realiza en caja.', 'prerequisites' => [
                ['key' => 'matricula_validada', 'type' => 'administrative_verification', 'name' => 'Validación de matrícula', 'description' => 'La matrícula debe ser validada previamente por el instituto.'],
            ]]),
        ],
        'TITULACION' => [
            $procedure('TITLE_PROF_TECH', 'Título Profesional Técnico', [
                $field('programa_estudios', 'Programa de estudios', 'career'),
                $field('condicion_egresado', 'Condición de egresado'),
                $field('fecha_egreso', 'Fecha de egreso', 'date'),
                $field('sistema_academico', 'Sistema académico'),
                $field('idioma_lengua', 'Idioma extranjero o lengua originaria'),
                $field('practicas_efsrt', 'Prácticas o EFSRT'),
                $field('intento_convocatoria', 'Intento o convocatoria'),
            ], [], [
                'reception_open' => false,
                'unavailable_message' => 'La recepción se habilitará en las fechas programadas por el instituto.',
                'instructions' => 'La información inicial es declarada por el solicitante y debe ser verificada por personal. Los requisitos de cada modalidad se cargarán en una fase posterior.',
                'variants' => [
                    ['code' => 'APPLICATION_WORK', 'name' => 'Trabajo de Aplicación Profesional'],
                    ['code' => 'PROFESSIONAL_EXAM', 'name' => 'Examen de Suficiencia Profesional'],
                ],
                'prerequisites' => [
                    ['key' => 'graduate_verification', 'type' => 'administrative_verification', 'name' => 'Verificación de condición de egresado', 'description' => 'La condición debe ser verificada por personal autorizado.'],
                ],
            ]),
        ],
    ],
];
