@extends('layouts.authenticated')
@section('title','Proceso de titulación')
@section('content')
<header class="mb-4"><span class="section-eyebrow">Título Profesional Técnico</span><h1 class="h2">{{ $titleProcess->procedureRequest->tracking_code }}</h1><span class="badge text-bg-primary">{{ $titleProcess->current_stage->label() }}</span></header>
@if($titleProcess->modality->value==='application_work')<section class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5">Trabajo de Aplicación Profesional</h2><p>Parámetros vigentes: hasta {{ config('title-process.application_work.max_members') }} integrantes; ejecución de {{ config('title-process.application_work.execution_months_min') }} a {{ config('title-process.application_work.execution_months_max') }} meses; similitud referencial máxima {{ config('title-process.application_work.similarity_max_percent') }} %; nota aprobatoria referencial {{ config('title-process.application_work.passing_grade') }}.</p>@if($project=$titleProcess->applicationWorkProject)<dl class="row mb-0"><dt class="col-sm-4">Proyecto</dt><dd class="col-sm-8">{{ $project->title }}</dd><dt class="col-sm-4">Etapa</dt><dd class="col-sm-8">{{ $project->current_stage->label() }}</dd><dt class="col-sm-4">Integrantes</dt><dd class="col-sm-8">{{ $project->members->count() }}</dd><dt class="col-sm-4">Asesor</dt><dd class="col-sm-8">{{ $project->assigned_advisor ?: $project->proposed_advisor }}</dd></dl>@else<p class="text-secondary mb-0">La propuesta aún no fue registrada.</p>@endif</div></section>@endif
<div class="row g-4"><main class="col-xl-8"><section class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5">Resumen</h2><dl class="row mb-0"><dt class="col-sm-5">Modalidad</dt><dd class="col-sm-7">{{ $titleProcess->modality->label() }}</dd><dt class="col-sm-5">Intento o convocatoria</dt><dd class="col-sm-7">{{ $titleProcess->attempt_or_call ?: 'No indicado' }}</dd><dt class="col-sm-5">Elegibilidad</dt><dd class="col-sm-7">Declarada por el solicitante{{ $titleProcess->eligibility_verified_at ? ' y verificada por personal' : '; pendiente de verificación' }}</dd><dt class="col-sm-5">Resultado</dt><dd class="col-sm-7">{{ $titleProcess->result ?: 'Pendiente' }}</dd></dl></div></section>
<section class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5">Historial de etapas</h2><ol class="timeline list-unstyled">@foreach($titleProcess->events->sortBy('created_at') as $event)<li class="timeline-item" tabindex="0"><strong>{{ $event->to_stage->label() }}</strong><p class="mb-1">{{ $event->description }}</p>@if($canManage)<small>Responsable: {{ $event->actor->first_name }} {{ $event->actor->last_name }}</small><br>@endif<time class="text-secondary small">{{ $event->created_at->format('d/m/Y H:i') }}</time></li>@endforeach</ol></div></section>
<section class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5">Programación</h2>@forelse($titleProcess->schedules->sortByDesc('scheduled_at') as $schedule)<div class="border-bottom py-2"><strong>{{ $schedule->scheduled_at->format('d/m/Y H:i') }}</strong> — {{ $schedule->place }} <span class="badge text-bg-light border">{{ $schedule->status }}</span>@if($schedule->reason)<p class="mb-0">{{ $schedule->reason }}</p>@endif</div>@empty<p class="text-secondary">Sin programación registrada.</p>@endforelse</div></section></main>
@if($canManage)<aside class="col-xl-4"><section class="card border-0 shadow-sm mb-3"><div class="card-body"><h2 class="h5">Verificar elegibilidad</h2><form method="POST" action="{{ route('title-processes.verify',$titleProcess) }}">@csrf @foreach(['graduate_status'=>'Condición de egresado','language'=>'Idioma o lengua','practice_efsrt'=>'Prácticas o EFSRT'] as $key=>$label)<div class="form-check mb-2"><input type="hidden" name="{{ $key }}" value="0"><input class="form-check-input" type="checkbox" id="{{ $key }}" name="{{ $key }}" value="1"><label class="form-check-label" for="{{ $key }}">{{ $label }} verificado</label></div>@endforeach<textarea class="form-control mb-2" name="observation" placeholder="Observación"></textarea><button class="btn btn-outline-primary">Registrar verificación</button></form></div></section>
<section class="card border-0 shadow-sm mb-3"><div class="card-body"><h2 class="h5">Cambiar etapa</h2><form method="POST" action="{{ route('title-processes.transition',$titleProcess) }}">@csrf<select class="form-select mb-2" name="stage" required>@foreach($stages as $stage)<option value="{{ $stage->value }}">{{ $stage->label() }}</option>@endforeach</select><textarea class="form-control mb-2" name="description" required placeholder="Motivo o constancia"></textarea><button class="btn btn-primary">Registrar etapa</button></form></div></section>
<section class="card border-0 shadow-sm mb-3"><div class="card-body"><h2 class="h5">Programar</h2><form method="POST" action="{{ route('title-processes.schedule',$titleProcess) }}">@csrf<input class="form-control mb-2" type="datetime-local" name="scheduled_at" required><input class="form-control mb-2" name="place" required placeholder="Lugar"><textarea class="form-control mb-2" name="reason" placeholder="Motivo"></textarea><button class="btn btn-primary">Programar</button></form></div></section>
<section class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5">Resultado</h2><form method="POST" action="{{ route('title-processes.result',$titleProcess) }}">@csrf<select class="form-select mb-2" name="result" required><option value="approved">Aprobado</option><option value="failed">Desaprobado</option><option value="absent">No se presentó</option><option value="rescheduled">Reprogramado</option><option value="observed">Observado</option></select><textarea class="form-control mb-2" name="observation" placeholder="Observación"></textarea><button class="btn btn-primary">Registrar resultado</button></form></div></section></aside>@endif</div>
@endsection
