@php($item = $procedureType)
<div class="row"><div class="col-md-4 mb-3"><label class="form-label" for="code">Código</label><input class="form-control" id="code" name="code" value="{{ old('code', $procedureType?->code) }}" maxlength="30" required></div><div class="col-md-8 mb-3"><label class="form-label" for="name">Nombre</label><input class="form-control" id="name" name="name" value="{{ old('name', $procedureType?->name) }}" maxlength="150" required></div></div>
<div class="row"><div class="col-md-6 mb-3"><label class="form-label">Categoría</label><select class="form-select" name="procedure_category_id"><option value="">Sin categoría</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('procedure_category_id', $procedureType?->procedure_category_id)==$category->id)>{{ $category->name }}</option>@endforeach</select></div><div class="col-md-6 mb-3"><label class="form-label">Modalidad</label><select class="form-select" name="presentation_modality_id"><option value="">Sin modalidad</option>@foreach($modalities as $modality)<option value="{{ $modality->id }}" @selected(old('presentation_modality_id', $procedureType?->presentation_modality_id)==$modality->id)>{{ $modality->name }}</option>@endforeach</select></div></div>
<div class="mb-3"><label class="form-label">Oficina responsable</label><select class="form-select" name="responsible_area_id"><option value="">Por confirmar</option>@foreach($areas as $area)<option value="{{ $area->id }}" @selected(old('responsible_area_id', $procedureType?->responsible_area_id)==$area->id)>{{ $area->name }}</option>@endforeach</select></div>
<div class="mb-3"><label class="form-label" for="description">Descripción</label><textarea class="form-control" id="description" name="description" rows="3" required>{{ old('description', $procedureType?->description) }}</textarea></div><div class="mb-3"><label class="form-label">Instrucciones</label><textarea class="form-control" name="instructions" rows="3">{{ old('instructions', $procedureType?->instructions) }}</textarea></div>
<div class="row"><div class="col-md-6 mb-3"><label class="form-label">Plazo de atención (días)</label><input class="form-control" name="attention_days" type="number" min="1" max="365" value="{{ old('attention_days', $procedureType?->attention_days) }}" required></div><div class="col-md-6 mb-3"><label class="form-label">Orden</label><input class="form-control" name="sort_order" type="number" min="0" value="{{ old('sort_order', $procedureType?->sort_order ?? 0) }}" required></div></div>
@include('admin.nested-catalog._availability-payment')
<fieldset class="border rounded p-3 mb-3"><legend class="h6">Presentación física</legend><div class="row"><div class="col-md-5 mb-3"><label class="form-label">Lugar</label><input class="form-control" name="physical_submission_location" value="{{ old('physical_submission_location', $procedureType?->physical_submission_location) }}"></div><div class="col-md-5 mb-3"><label class="form-label">Horario</label><input class="form-control" name="physical_submission_schedule" value="{{ old('physical_submission_schedule', $procedureType?->physical_submission_schedule) }}"></div><div class="col-md-2 mb-3"><label class="form-label">Plazo (días)</label><input class="form-control" type="number" min="1" max="365" name="physical_submission_deadline_days" value="{{ old('physical_submission_deadline_days', $procedureType?->physical_submission_deadline_days) }}"></div></div></fieldset>
@if($errors->any())<div class="alert alert-danger mt-3"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="d-flex flex-wrap gap-2 mt-4"><button class="btn btn-primary" type="submit">{{ $submitLabel }}</button><a class="btn btn-outline-secondary" href="{{ route('admin.procedure-types.index') }}">Cancelar</a></div>
