@extends('layouts.authenticated')
@section('title', 'Trámites')
@section('content')
<x-admin.catalog-header title="Trámites" description="Configura categorías, modalidades, variantes, requisitos, campos y prerrequisitos." :create-route="route('admin.procedure-types.create')" create-label="Crear trámite" />
<div class="d-flex flex-wrap gap-2 mb-3"><a class="btn btn-outline-primary" href="{{ route('admin.procedure-categories.index') }}">Categorías</a><a class="btn btn-outline-primary" href="{{ route('admin.presentation-modalities.index') }}">Modalidades</a></div>
<div class="card border-0 shadow-sm"><div class="card-body border-bottom"><form class="row g-2" method="GET" role="search"><div class="col-md-8"><label class="form-label" for="buscar">Buscar</label><input class="form-control" id="buscar" name="buscar" value="{{ $search }}"></div><div class="col-md-auto align-self-end"><button class="btn btn-primary">Buscar</button></div></form></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Trámite</th><th>Configuración</th><th>Elementos</th><th>Estado</th><th class="text-end">Acciones</th></tr></thead><tbody>
@forelse($procedureTypes as $procedureType)<tr><td><code>{{ $procedureType->code }}</code><strong class="d-block">{{ $procedureType->name }}</strong><small>{{ $procedureType->category?->name ?? 'Sin categoría' }}</small></td><td>{{ $procedureType->presentationModality?->name ?? 'Sin modalidad' }}<small class="d-block">{{ $procedureType->attention_days }} días · orden {{ $procedureType->sort_order }}</small>@if($procedureType->requires_payment)<small>{{ $procedureType->currency }} {{ $procedureType->amount }}</small>@endif</td><td>{{ $procedureType->requirements_count }} requisitos<small class="d-block">{{ $procedureType->variants_count }} variantes</small></td><td><x-catalog-status :active="$procedureType->active" /></td><td class="text-end"><div class="d-inline-flex flex-wrap justify-content-end gap-1"><a class="btn btn-sm btn-outline-secondary" href="{{ route('admin.procedure-types.requirements.index', $procedureType) }}">Requisitos</a><a class="btn btn-sm btn-outline-secondary" href="{{ route('admin.procedure-types.variants.index', $procedureType) }}">Variantes</a><a class="btn btn-sm btn-outline-secondary" href="{{ route('admin.procedure-types.dynamic-fields.index', $procedureType) }}">Campos</a><a class="btn btn-sm btn-outline-secondary" href="{{ route('admin.procedure-types.prerequisites.index', $procedureType) }}">Prerrequisitos</a><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.procedure-types.edit', $procedureType) }}">Editar</a><form method="POST" action="{{ route('admin.procedure-types.toggle', $procedureType) }}" data-confirm-submit="¿Confirmas el cambio de estado?">@csrf @method('PATCH')<button class="btn btn-sm {{ $procedureType->active ? 'btn-outline-danger' : 'btn-outline-success' }}">{{ $procedureType->active ? 'Desactivar' : 'Activar' }}</button></form></div></td></tr>
@empty<tr><td colspan="5" class="text-center py-4">No se encontraron trámites.</td></tr>@endforelse
</tbody></table></div>@if($procedureTypes->hasPages())<div class="card-footer bg-white">{{ $procedureTypes->links() }}</div>@endif</div>
@endsection
